### ISSUE TITLE
Design slide layouts

### ISSUE THREAD

**Issue by xaprb** [xaprb/remarkjs-themes#8]
This is a project to build a CSS layout-only framework for Remark, called Apron. Users will be able to use CSS classes and div’s to create flexible slide layouts with minimal syntax and minimal interference with Remark’s own styling and functionality

I want to be able to build the following nine layouts as a baseline, by combining the building blocks in various ways.

<img width="859" alt="screen shot 2018-05-27 at 8 19 37 pm" src="https://user-images.githubusercontent.com/279875/40592309-b01b94c2-61eb-11e8-8f53-185a4e93a1f8.png">

Each container in the illustration can be used for any purpose, for example a box can have text or an image -- there is no special image placeholder. I also think the slide padding should be up to the theme: for example the title and subtitle could be full-bleed to the right and left edges; in layout 4 the image could be full-width too. Those should be user-configurable. The lines around the content areas are simply for illustration purposes, I don’t really want them to be visible. And there’s no difference between header containers and body containers—no separate boxes for the title and list in layout 3 for example.

There’s a number of requirements and constraints that I want to satisfy.

Remark functionality we don’t want to disrupt:
* Incremental slide builds with two dashes `--` as slide separators—this only works if the content isn’t wrapped in a div. Therefore, prefer to avoid div’s unless necessary.

Remark extensions to Markdown syntax that we can use:
* Div’s with one or more CSS classes, as wrappers, using `.class1[content]` syntax; multiple classes are added to the div with `.class1.class2[…]` syntax.
* Multiple-nested div’s
* span’s with one or more CSS classes, just like div’s
* Slide-level CSS classes—we can add as many CSS classes as we want to the div that contains the slide layout.

Things we can’t do or don’t want to do:
* We can’t add classes to img tags.
* We don’t want to use raw HTML, we want to use Markdown syntax.
* We don’t want to wrap things in div’s if we can avoid it.
* Given a tradeoff between complicating things a lot or forcing common use cases to be more complicated, versus a small incremental gain in flexibility or power, we’ll stick with the simpler, more limited option. For example, if there is a rare type of layout that someone might want, but it forces common layouts to use nested div’s, we will probably decide not to do it so that the common layouts are simpler.
* Don’t reset, strip, replace, or interfere with Remark’s styling unless absolutely needed.
* Don’t specify things like fonts, font sizes, or colors. Users will provide this separately in themes that build upon Apron.

Functionality desired:
* Remove padding/margin from the slide container element (`<div class="remark-slide-content">`) so full-bleed layouts are possible: `class: p0` to remove padding and put a full-height image on the left half of the slide, for example.
* Build grids by putting div’s of various widths and heights, in increments of 1/12th of the slide’s width or height. Any combinations of classes called `.w1` to `.w12` and/or `.h1` to `.h12` should be possible, like `.w4`, `.h2`, `.w6.h6` or so on. If needed, combining them is fine: `.w4-h8` for example.
* Make images fill the div that contains them, clipping the overflow (`object-fit:cover`) by default. This will make it possible to make a full-bleed image on the right or left half of the slide, for example, simply by creating a div and putting an image in it.
* Make an optional CSS class for a wrapper div of a given size, that will make the image shrink to fit within the div (`object-fit: scale-down`). This will allow creating, for example, a two-column layout and putting a high-resolution image within it, mixed with text.
* Make classes that will float (or absolute-position) a div to the left or right, of any desired height, either within the slide’s padded area or flush/fullbleed against the edges/top/bottom. This way an image or content in a column can be placed first in the markup wrapped in a div of the desired width, and then incremental content can be added after that to be revealed step by step, *not* wrapped in a div.
* Allow adding padding to div’s that mimics the padding that can be stripped from the slide for full-bleed layouts. So if I use `class: p0` to strip padding from the slide, then create an image collage along the top of the slide, perhaps I want the bottom portion of the slide to have text inside it, with normal padding that looks like RemarkJS’s defaults. I would use for example, `w12.h6.p1[… content …]` to cover the bottom half of the slide with a normally padded and normally spaced content area.
* A class that will make the text in a slide and/or a div about 2/3rds the normal font size, for slides that have a lot of text or a very long headline that will otherwise wrap. This should still work after users specify their desired fonts and font sizes. This is a nice-to-have, and if it isn’t easy/obvious, then skip it.
* Both 16:9 and 4:3 slide ratios should be supported.
* As a special case, make *slide* classes for two-column and three-column layouts that will work with a header, followed by two or three block-level elements such as UL or IMG tags, so flat markdown without any div's will format nicely into two or three columns depending on the class name, e.g. `class: two-column` or `class: three-column`. This is optional/extra.

I created a demo slideshow that shows potential/concept markup for the 9 layouts above. The file is here: https://raw.githubusercontent.com/xaprb/remarkjs-themes/master/demo.html and there's also an image that is included in it.

**Comment by xaprb** [comment]
I think the layouts can be done with a combination of the following.

Slide classes:

1. title; puts heading elements middle and center.
2. fullbleed: removes margin and padding from slides, allowing full-bleed layouts like layout 9.

Box (div) classes:

1. Similar to familiar bootstrap or CSS grid layouts, where the slide is divided into 12 columns, and you can use .col-1 for 1/12th, .col-12 for full width, and anything in between.

From my experience that should work fine and should be usable to generate any of the layouts, and combinations of them such as a one-column layout for the upper half of the slide and two-col for the bottom, like this:

<img width="618" alt="two-column-combo" src="https://user-images.githubusercontent.com/279875/40592401-d45b4a84-61ec-11e8-80ae-e081fb503606.png">


I don't know how to do all of this in CSS, but now I can learn.

**Comment by xaprb** [comment]
To be clear, I don't plan to build nine CSS classes that will generate those nine layouts. I'll build a couple of slide classes and a couple of div classes and that should let anyone build those layouts, plus any others that they want to.

**Comment by xaprb** [comment]
A couple of things I will want, if possible:

* The ability to make an image full-bleed and clip to the div that contains it, without distorting its aspect ratio, similar to background-size set to cover.
* The ability to clip text overflow in a div. And ideally, to shrink text when the div is too full.

**Comment by xaprb** [comment]
Slides that have a combination of full-bleed content, and content that has padding keeping it away from the edges of the slide, will be interesting. Perhaps I'll need wrapper div classes to add padding. For example, an image-right might be something like the following:

```
.col-8[
.padded[
# A header
* A content bullet
* Another bullet
]
]
.col-4[
![Image](image.png)
]
```

**Comment by xaprb** [comment]
Looks like [object-fit](https://caniuse.com/#search=object-fit) is the right way to do image resizing to fit within a div.

**Comment by xaprb** [comment]
There's a couple of details I've forgotten:

1. CSS classes to reduce text size in a div
2. CSS classes to limit the height of an image; I often want to set an image's height to 450 or 300 so as to shrink it to fit vertically into a slide

**Comment by xaprb** [comment]
object-fit is the correct way to do it. In [the current CSS](https://github.com/xaprb/remarkjs-themes/blob/7c57afc275a7fb177a7457ba2773f808b076ee0c/monobloc.css#L93), this works okay to full-bleed and full-height an image on the right third of a slide:

    .rc[<img src=unsplash-photos-FoKO4DpXamQ.jpg style="height: 100%; width: 100%; object-fit: cover; display: block">]

**Comment by xaprb** [comment]
Here's the padding in Remark's default CSS, which will have to be neutralized

<img width="1136" alt="screen shot 2018-06-01 at 6 53 40 am" src="https://user-images.githubusercontent.com/279875/40837626-17d2e3c4-6569-11e8-9a47-9bbef8e6b149.png">

**Comment by xaprb** [comment]
When I mentioned the CSS layout grid above, I was thinking of something like this:

* [GitHub - zachacole/Simple-Grid: A simple, lightweight CSS grid](https://github.com/zachacole/Simple-Grid)

But I'm not sure that is suitable. Do I really need/want to have markups like this:

```
---
# My slide heading
.row[
.col-6[
# Left title
* some
* bullets
]
.col-6[
# Right title
* some
* other
* bullets
]
]
```

I don't really like the need to have a `.row[...]` wrapper div there.

And will this even work? Can I build layout 9 with this? Would it be, for example... this?

```
---
class: full-bleed
.row[
.col-8[
![Left Side Image](left-image.jpg)
]
.col-4[
 // two images stack on top of each other in this right-hand column.
 // How do you even split a column across the middle horizontally
 // into two boxes/rows of equal height, stacked on top of each other?
 // I don't know.
]
]
```

**Comment by xaprb** [comment]
I created a demo slideshow:
https://www.xaprb.com/slides/demo-remarkjs-slideshow/
The source is at
https://github.com/xaprb/xaprb-src/tree/master/content/slides/demo-remarkjs-slideshow

**Comment by Saif-AL-Tahawy** [comment]
I'm proud to finish this Stylesheet and work for you and finish this Project.
It's a Big Success in my Life Story I'll stay Remember it.
Thanks again for the opportunity which you gave me to Build This Project.
